### PR TITLE
Parameter valuefor ci merge

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
This PR allows the proper description of parameters for the ros and the system model. The supported types are:

* Boolean (true or false)
* Integer 
* Double
* String
* Base64
* List 
* Array
* Struc

For ros model the format is the following:

**Parameter** {**name** NAMEforPARAMETER **type** TYPEfromTHElistABOVE {**default** DEFAULTVALUE}}

where the default value is optional.
Examples:
```
Parameter { name 'frame_id' type String },
Parameter { name 'int_example' type Integer },
Parameter { name 'double_example' type Double },
Parameter { name 'color' type List {Integer,Integer,Integer,Integer}},
Parameter { name 'struc_example' type Struc {
            'topic' String,
            'priority' Integer,
            'name' String,
            'timeout' Double}}
```

For the ros system model (within a component interface) the format is the following:
 **RosParameter** NAMEforPARAMETER {**RefParameter** 'REFtoPARAMETERdefiniton' **value** PARAMETERVALUE}

where the  value is optional.
Examples:
```
RosParameter '/base/frame_id' {RefParameter 'package_name.parameters_node.parameters_node.frame_id' value 'base_link'
RosParameter '/gazebo_gui/sor_pgs_iters' {RefParameter 'package_name.parameters_node.parameters_node.int_example' value 50},
RosParameter '/gazebo_gui/gravity_x' {RefParameter 'package_name.parameters_node.parameters_node.double_example' value 0.0},
RosParameter 'light/blue' {RefParameter 'package_name.parameters_node.parameters_node.color' value {0, 0, 1, 1}},
RosParameter '/base/twist_mux/topics' {RefParameter 'package_name.parameters_node.parameters_node.struc_example' value {
                  { 'topic' { value 'twist_mux/command_safe'}},
                  { 'name' { value 'collision_velocity_filter'}},
                  { 'priority' { value 10}},
                  { 'timeout' { value 0.25}}}},
```

Some rules check the correct set of parameters (if the type of the given value is the expected one) this is working correctly for all the basic primitive types (String, Boolean, Double...) but has some errors for some combinations, like strucs of strucs (recognized as Lists or sequences(?)), strucs composed by list of lists....

All of the possible combinations have to be extensively tested and debugged, alternatively for now the validation of the DSL can be temporally disable...

**Comment by ipa-nhg** [comment]
fixed all the problems for the validator, tested and working for all the cases and their combinations :+1:

**Comment by ipa-nhg** [comment]
@chcorbato @ipa-hsd all the issues are fixed and the new version works for all the parameter types. 
I have also created a new official release ( [v 1.2.1](http://ros-model.seronet-project.de/updatesite/latest/) ) which includes the parameters features.

**Comment by ipa-hsd** [comment]
> fixed all the problems for the validator, tested and working for all the cases and their combinations +1

`all the cases and their combinations`: are these the ones mentioned in the examples in https://github.com/ipa320/ros-model/pull/93#issuecomment-588161717  
Or there could be more combinations?

**Comment by ipa-nhg** [comment]
With "all the cases" I mean all the primitives mentioned in https://github.com/ipa320/ros-model/pull/93#issuecomment-588161717 as bullet points, and all the possible combinations for Lists and Strucs.

I have created an example file with all of them. 

**test_parameters.ros**

```
PackageSet { package {
  CatkinPackage test_parameters{ artifact {
    Artifact  test_parameters {
       node Node  { name dfsfds
         parameter { 
           Parameter { name string_test type String },
           Parameter { name bool_tets type Boolean },
           Parameter { name array_tets type Array {type String}},
           Parameter { name base64_test type Base64},
           Parameter { name double_test type Double},
           Parameter {name int_test type Integer},
           Parameter {name list_test type List {Integer,Integer,String}},
           Parameter {name struc_test type Struc 
               {first_element Integer ,
               second_element List { Integer, String},
               third_element String ,
               last_element Struc { hola Integer, what String}}
           }}}
}}}}}
```
**test_parameters_system.rossystem**
```
RosSystem { Name 'test_parameters_system' 
  RosComponents ( 
    ComponentInterface {
      name test_param_component
        RosParameters {
          RosParameter { 
            RefParameter "test_parameters.test_parameters.dfsfds.string_test" value test},
          RosParameter {
            RefParameter "test_parameters.test_parameters.dfsfds.bool_tets" value true },
          RosParameter {
            RefParameter "test_parameters.test_parameters.dfsfds.double_test" value 3.14 },
          RosParameter {
            RefParameter "test_parameters.test_parameters.dfsfds.base64_test" value 0b01 },
          RosParameter {
            RefParameter "test_parameters.test_parameters.dfsfds.int_test" value 5 },
          RosParameter {
            RefParameter "test_parameters.test_parameters.dfsfds.list_test" value  {1,2,test}},
          RosParameter {
            RefParameter "test_parameters.test_parameters.dfsfds.struc_test" value {
              { second_element {value{1,dsad}}},
              { last_element { value { 
                 { hola {value 3} },
                 { what {value sd} } 
}}}}}}})
}
```

**Comment by ipa-hsd** [comment]
Thanks this would be helpful!

**Pull request merged**
