### PR TITLE
Add the attribute "FromGitRepo" and add first version for the .rosinstall generator for ROS1

### PR DESCRIPTION
**Pull request by ipa-nhg**
@ipa-rwu I have added a first version for the rosinstall generator you need. I added a new field to the Package called "FromGitRepo" and if the user defined for a Ros Package this attribute then I add the repo to the .rosinstall file. I have also redefined the attribute "Dependencies" to allow that the user can use that this to define the dependencies of my package that are not released. In other words, see this example:

```
PackageSet {
	CatkinPackage ur_msgs {
		FromGitRepo "https://github.com/ros-industrial/universal_robot"
	},
	CatkinPackage ur_robot_driver{
		FromGitRepo "https://github.com/UniversalRobots/Universal_Robots_ROS_Driver"
		Dependencies { ur_msgs }
		Artifact  ur_robot_driver_node {
		Node { name ur_hardware_interface
		.....
}}
```

for this example if you add the ur_hardware_interface node to a system, the following .rosinstall file will be auto-generated:

```
- git: {local-name: Universal_Robots_ROS_Driver, uri: 'https://github.com/UniversalRobots/Universal_Robots_ROS_Driver'}
- git: {local-name: universal_robot, uri: 'https://github.com/ros-industrial/universal_robot'}
```

See: https://github.com/ipa-nhg/ros-model-examples/commit/3d00d0db038e2ea073a93d1b3b7e1ebdcc9ee80c

@ipa-rwu what do you think? is this a good start point? 

The definition of the branches in missed and probably we need to generate another docker file to deal with this .rosinstall file.

From all the changes probably the only part relevant to you is: https://github.com/ipa-nhg/ros-model/blob/422976308b273bcec84f4399f1ec9d58ecb6ce22/plugins/de.fraunhofer.ipa.rossystem.xtext/src/de/fraunhofer/ipa/rossystem/generator/RosInstallCompiler.xtend

### CODE REVIEW

**Comment by ipa-nhg** [comment]
@ipa-hsd FYI

**Comment by ipa-hsd** [comment]
Should we follow the [rosinstall format](https://docs.ros.org/en/independent/api/rosinstall/html/rosinstall_file_format.html) and add the version (tag, commit hash or branch) as well?

**Comment by ipa-rwu** [comment]
I think it is a good starting point. 
1. As Harshed said, I also need the branch name, e.g. 
`- git: {local-name: fmauch_universal_robot, uri: 'https://github.com/fmauch/universal_robot.git', version: calibration_devel}`
2. local-name == repo_name?
3. [Universal_Robots_ROS_Driver](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver) needs several dependencies from [fmauch/universal_robot](https://github.com/fmauch/universal_robot/tree/calibration_devel). But user only needs to define one of the dependencies, right?

**Comment by ipa-hsd** [comment]
@ipa-rwu says:
> local-name == repo_name?

For the `Universal_Robots_ROS_Driver` example, 
```
# clone fork of the description. This is currently necessary, until the changes are merged upstream.
$ git clone -b calibration_devel https://github.com/fmauch/universal_robot.git src/fmauch_universal_robot
```
`fmauch_universal_robot` would be the local name.  

> Universal_Robots_ROS_Driver needs several dependencies from fmauch/universal_robot. 

This should be added in the `.rosinstall` file which you already mentioned in your 1st point (did I understand that correctly?)

**Comment by ipa-rwu** [comment]
> @ipa-rwu says:
> 
> > local-name == repo_name?
> 
> For the `Universal_Robots_ROS_Driver` example,
> 
> ```
> # clone fork of the description. This is currently necessary, until the changes are merged upstream.
> $ git clone -b calibration_devel https://github.com/fmauch/universal_robot.git src/fmauch_universal_robot
> ```
> 
> `fmauch_universal_robot` would be the local name.
> 
> > Universal_Robots_ROS_Driver needs several dependencies from fmauch/universal_robot.
> 
> This should be added in the `.rosinstall` file which you already mentioned in your 1st point (did I understand that correctly?)

As you show in the [rosinstall format](https://docs.ros.org/en/independent/api/rosinstall/html/rosinstall_file_format.html), it needs **local_name**, **uri** and **version**.

For **local_name**, it is the folder name or folder path. In the example from Nadia, **local_name** is **repo name**. But the example from you,  **local_name** was redefined as a custom name. 

And **version** is **branch name**

**Comment by ipa-nhg** [comment]
@ipa-hsd  @ipa-rwu  Thanks for your comments.

Yes, you are right from the format of a rosinstall file I am missing local-name and version:
- for local-name  I decided to just use the name of the repository, for simplification. I think that in the 99% of the cases we all use the name of the repo. If you think this is a relevant point we can add it as an optional attribute. And if not defined then we take the name of the repo by default.
- the version (=branch, =commit tag) is missed and needed, I wrote it also on my initial comment. According to the rest of my grammar and for consistency we should have something like:

`FromGitRepo { url https://github.com/UniversalRobots/Universal_Robots_ROS_Driver version WhatEver}`

  But I am not sure if I like it, I was thinking on a single string that we can interpret (obviously we will have to add some help to show the people how to set the branch), for example:

  `FromGitRepo "https://github.com/UniversalRobots/Universal_Robots_ROS_Driver:WhatEver"`

  or 

  `FromGitRepo "https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/WhatEver"`

what do you think?

**Comment by ipa-rwu** [comment]
> @ipa-hsd @ipa-rwu Thanks for your comments.
> 
> Yes, you are right from the format of a rosinstall file I am missing local-name and version:
> 
> * for local-name  I decided to just use the name of the repository, for simplification. I think that in the 99% of the cases we all use the name of the repo. If you think this is a relevant point we can add it as an optional attribute. And if not defined then we take the name of the repo by default.
> * the version (=branch, =commit tag) is missed and needed, I wrote it also on my initial comment. According to the rest of my grammar and for consistency we should have something like:
> 
> `FromGitRepo { url https://github.com/UniversalRobots/Universal_Robots_ROS_Driver version WhatEver}`
> 
> But I am not sure if I like it, I was thinking on a single string that we can interpret (obviously we will have to add some help to show the people how to set the branch), for example:
> 
> `FromGitRepo "https://github.com/UniversalRobots/Universal_Robots_ROS_Driver:WhatEver"`
> 
> or
> 
> `FromGitRepo "https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/WhatEver"`
> 
> what do you think?

How can we define the branch?

**Comment by ipa-hsd** [comment]
```
FromGitRepo "https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/WhatEver"
```
is a bit confusing. I would prefer the 1st option.

**Comment by ipa-hsd** [comment]
@ipa-nhg nice! Could you please change the PR to https://github.com/ipa-nhg/ros-model/tree/rosinstallGenerator

**Comment by ipa-rwu** [comment]
> @ipa-rwu nice! Could you please change the PR to https://github.com/ipa-nhg/ros-model/tree/rosinstallGenerator

Done, then I will close this PR

**Pull request merged**
